name: saltstack-haproxy-formula
source: https://github.com/bechtoldt/saltstack-haproxy-formula
summary: SaltStack formula to set up and configure haproxy, a TCP/HTTP reverse proxy and load balancer
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
